### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by nparsons08** [fizzed/font-mfizz#12]
Please add a Magento icon :)

**Comment by jjlauer** [comment]
v2.0 is out and most importantly there are instructions for building & contributing to the font directly.  This project is 100% a hobby and I'm happy to publish builds, but I'll rely on the open source community to add more icons.  Please see README.md and DEVELOPMENT.md for more info.

**Comment by jjlauer** [comment]
Latest v2.4.1 release includes this icon.  You can preview it here http://fizzed.com/oss/font-mfizz
