### ISSUE TITLE
C/C++/C# icons

### ISSUE THREAD

**Issue by ioquatix** [fizzed/font-mfizz#14]
Hi, thanks for the awesome work.

The icons for C/C++ and C#  could use some work.

They don't look that great when vertically aligned.

Sorry I can't help much, but thought I'd mention it.

![image](https://cloud.githubusercontent.com/assets/30030/3668070/4bda908e-1213-11e4-97c3-d766a49244b1.png)

**Comment by jjlauer** [comment]
Well, vertical alignment never was a design goal I suppose.  You'd have a similar issue with using a non-monospaced font  and letters like G vs. A.  The best workaround I could think is to left align & fix the width?

**Comment by ioquatix** [comment]
I guess one option would be to normalise the letter C thickness and perhaps putting a box around them and centering within the box?
