### ISSUE TITLE
ISC or MIT license?

### ISSUE THREAD

**Issue by maruilian11** [fizzed/font-mfizz#36]
hi, recently we want to add your lib on https://cdnjs.com, i saw ISC license is mentioned in [package.json](https://github.com/fizzed/font-mfizz/blob/v2.2/package.json#L14), but MIT license in [`src`](https://github.com/fizzed/font-mfizz/blob/v2.2/src/LICENSE.txt), just want to confirm this with you.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6635

**Comment by jjlauer** [comment]
MIT license.  Will fix package.json.

That's really cool you are going to host it.  Is there anything I can put
in the README file to point users to your CDN?  How do I make sure updates
get propagated out to it?

-Joe

**Comment by maruilian11** [comment]
hi, we will close https://github.com/cdnjs/cdnjs/issues/6635 after adding your lib, and i will tag you in commit message, we hope you can review the PR before it is merged.
if you can mention the CDN lib link in your readme.md, that will be great!
we use **git auto-update** depending on **git tags** or **npm auto-update**, we prefer npm auto-update, so if your lib is on npm, please let me know, thank you!

we're going to use git auto-update in your lib, so just keep the git tags the latest version, the lib will update smoothly. and if you find there is any problem on the website, just open an issue, we will handle it as fast as we can.
