### ISSUE TITLE
MongoDB Icon

### ISSUE THREAD

**Issue by xFlatlinex** [fizzed/font-mfizz#4]
MongoDB logo would be great.
You can get the logo from [here](https://www.mongodb.com/brand-resources).

**Comment by bomb-on** [comment]
Do you think you can use this one for MongoDB maybe?
https://drive.google.com/file/d/0B05CtuPSMsUgVXppSTBiV1dDNzA/view?usp=sharing

**Comment by xFlatlinex** [comment]
There's a download link in the MongoDB page I passed which contains EPS files.
Here's the direct link to the download http://info.mongodb.com/rs/mongodb/images/MongoDB_Brand_Resources.zip

**Comment by jjlauer** [comment]
In v2.0
