### ISSUE TITLE
I packed Font-Mfizz as a Ruby Gem 

### ISSUE THREAD

**Issue by gingerhot** [fizzed/font-mfizz#54]
I run into Font-Mfizz when I need some icons for programming languages in one of my Rails projects. Then I packed it as a Ruby Gem months ago.

Here it is:  https://rubygems.org/gems/font-mfizz-rails                    
https://github.com/gingerhot/font-mfizz-rails

I release new version with the release of Font-Mfizz here. 

It will be very convenient to put a link in your README or website for more guys to use it. 

Thanks~

**Comment by jjlauer** [comment]
@gingerhot That's awesome.  Added it to the main README.md
